# Generated by Django 5.2 on 2026-04-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0004_alter_movie_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='text',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
